url: 'https://karo-fox.github.io'
baseurl: ''
title: 'karo-fox blog'

date_locale: pl

collections:
  posts:
    output: true
    permalink: /posts/:title/

plugins:
  - jekyll-postcss
  - jekyll-polyglot

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
  - vendor

include:
 - _pages

# Polyglot settings
languages: ["pl", "en"]
default_lang: "pl"
exclude_from_localization: ["javascript", "images", "css", "public"] 
parallel_localization: true

sep: "|"