url: 'https://karo-fox.github.io'
baseurl: 'karo-fox.github.io'
title: 'karo-fox blog'

date_locale: pl

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json

include:
 - _pages
 - _sass